% %%%%% Energy per atom using extended finnis and sinclair potential (Tantalum) %%%%%
% 
% % embedding energy parameters
% A=2.7020029; d=4.15;           %%d=4.07698;
% 
% rr = 0:0.01:8;
% phi1=[];phi2=[];
% 
% %neighbor 1
% for j=1:length(rr)
% r=sqrt(3)/2*rr(j);
% if (r<d)
% phi = A.^2.*(r-d).^2;
% phi1 = [phi1 phi];
% else
% phi=0;
% phi1=[phi1 phi];
% 
% end
% end
% 
% %neighbor 2
% for j=1:length(rr)
% r=rr(j);
% if (r<d)
% phi = A.^2.*(r-d).^2;
% phi2 = [phi2 phi];
% else
% phi=0;
% phi2=[phi2 phi];
% 
% end
% end
% 
% 
% V_pair1 =[]; V_pair2=[];
% % pair-potential parameters
% c=3.77; c0 = 30.91155; c1 = -26.57902; c2 = 6.651629; c3 = 0.0070699 ; c4 = -0.128597;
% 
% %neighbor 1
% for j=1:length(rr)
%     r=sqrt(3)/2*rr(j);
%  if(r<c)
%   V = (r-c).^2.*(c0 + c1.*r + c2.*r.^2 + c3.*r.^3 + c4.*r.^4);
%   V_pair1=[V_pair1 V];
%  else
%   V=0;
%   V_pair1 = [V_pair1 V];
%  end
% end
% 
% %neighbor 2
% for j=1:length(rr)
%     r=rr(j);
%  if(r<c)
%   V = (r-c).^2.*(c0 + c1.*r + c2.*r.^2 + c3.*r.^3 + c4.*r.^4);
%   V_pair2=[V_pair2 V];
%  else
%   V=0;
%   V_pair2 = [V_pair2, V];
%  end
% end
% 
% Utot = 4*V_pair1 + 3*V_pair2 - sqrt(8*phi1) - sqrt(6*phi2);
% 
% figure(10)
% hold on
% plot(rr,Utot,'--k')


%%%%% Tabulate the data for the original FS potential %%%%%

%%%% Embedding function %%%%
nrho = 10000;drho =7.5*0.1664185884538253E-02;
rho = 0:drho:drho*(nrho-1); 
F_pot = - sqrt(rho);

arr_fs=[];
%%% tabulate F_pot %%%
for jj=1:2000
    ii = 5*(jj-1) + 1: 5*jj;
    arr_fs=[arr_fs; F_pot(ii)];
end

%% electron density parameters
A = 2.591061; d = 4.076980; rend=5;

nr=10000; dr = rend/(nr-1);
rr=0:dr:rend;
%

%rho_pot = A^2.*(r-d).^2;
rho_pot=[];
for j=1:length(rr)
    r=rr(j);
 if(r<d)
  rho = A^2.*(r-d).^2;
  rho_pot=[rho_pot rho];
 else
  rho = 0;
  rho_pot=[rho_pot rho];
 end
end


%%% tabulate rho_pot %%%%%
for jj=1:2000
    ii = 5*(jj-1) + 1: 5*jj;
    arr_fs=[arr_fs; rho_pot(ii)];
end


%% pair-potential parameters
c=4.20; c0 = 1.2157373; c1 = 0.0271471; c2 = -0.1217350; c3 = 0; c4 = 0;
%c=3.77;

%%% pair potential %%%%
%nr=5000; dr = rend/(nr-1);
rr=0:dr:rend;

%V = (r-c).^2.*(c0 + c1.*r + c2.*r.^2 + c3.*r.^3 + c4.*r.^4);
V_pair=[];
for j=1:length(rr)
    r=rr(j);
 if(r<c)
  V = (r-c).^2.*(c0 + c1.*r + c2.*r.^2 + c3.*r.^3 + c4.*r.^4);
  V_pair=[V_pair V];
 else
  V = 0;
  V_pair=[V_pair V];
 end
end
pair_pot =  V_pair.*rr;

%%% tabulate pair potential %%%
for jj=1:2000
    ii = 5*(jj-1) + 1: 5*jj;
    arr_fs=[arr_fs; pair_pot(ii)];
end


% ****************************************************
% Adapt and write into a new data file.
% ****************************************************
% An empty line has to be manually written after each line input

data_out_file_name = 'Ta_orig_FS.eam2.alloy'; % output data file
data_out_file_ID = fopen(data_out_file_name,'w');



%%%%% rewrite the first 6 lines %%%%%
dataArray{1}{1} = 'Ta2 EAM/FS model';
dataArray{1}{2} = 'Original finnis and sinclair parameters';
dataArray{1}{3} = 'Generated by matlab';
dataArray{1}{4} = '1  Ta';
dataArray{1}{5} = '10000  1.2481394134037E-02  10000  5.000500050005001e-04  0.4200000E+01';
dataArray{1}{6} = '73     180.95         3.304    bcc';
%%%%%%%%%%%%%%%%%%

for line = 1:6
    fprintf(data_out_file_ID, dataArray{1}{line});
    fprintf(data_out_file_ID, '\n');
end


for k=1:6000
    data = arr_fs(k,:);
    str_data = num2str(data);
% 
%     % print this grain to file
    fprintf(data_out_file_ID, str_data);
    fprintf(data_out_file_ID, '\n');
end


%Natom_initial = atom_count;
% end

fclose(data_out_file_ID);

